"""empty message

Revision ID: 5d2fe0bbb559
Revises: 443d163989e8
Create Date: 2020-02-19 16:27:04.244996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d2fe0bbb559'
down_revision = '443d163989e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('full_text', sa.String(length=500), nullable=True))
    op.drop_column('tweet', 'status')
    op.drop_column('tweet', 'user_name')
    op.add_column('user', sa.Column('followers_count', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('latest_tweet_id', sa.BigInteger(), nullable=True))
    op.add_column('user', sa.Column('screen_name', sa.String(length=128), nullable=True))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('user', 'screen_name')
    op.drop_column('user', 'latest_tweet_id')
    op.drop_column('user', 'followers_count')
    op.add_column('tweet', sa.Column('user_name', sa.VARCHAR(), nullable=True))
    op.add_column('tweet', sa.Column('status', sa.VARCHAR(), nullable=True))
    op.drop_column('tweet', 'full_text')
    # ### end Alembic commands ###
